name: Run JMeter Test

on: [push, pull_request]

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    services:
        postgres:
          image: postgres:13
          env:
            POSTGRES_USER: diego
            POSTGRES_PASSWORD:  haipriori1
            POSTGRES_DB: test_db
          ports:
            - 5432:5432
          options: >-
            --health-cmd="pg_isready -U diego"
            --health-interval=10s
            --health-timeout=5s
            --health-retries=5
    env:
        PORT: 5001
        DB_HOST: localhost
        DB_PORT: 5432
        DB_USER: diego
        DB_PASS: haipriori1
        DB_NAME: test_db
        JWT_SECRET: 'd0cvn28bmd41ueiqd8a#023n9da89&'
        NEXT_PUBLIC_API_BASE_URL: http://localhost:5001

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Client Dependencies
        working-directory: ./client
        run: npm install

      - name: Build 
        working-directory: ./client
        run: npm run build

      - name: Run frontend on background
        working-directory: ./client
        run: npm run dev & PIDF=$! && sleep 10 && kill -SIGINT $PIDF

      - name: Install backend dependencies
        working-directory: ./server
        run: npm install 

      - name: Run backend on background
        working-directory: ./server
        run: npm run start:dev & PIDB=$! && sleep 10 && kill -SIGINT $PIDB 

      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre-headless wget unzip
          wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.3.zip
          unzip apache-jmeter-5.6.3.zip
          echo "$PWD/apache-jmeter-5.6.3/bin" >> $GITHUB_PATH

      - name: Run JMeter Test Plan
        run: |
          jmeter -n -t homepage-load50.jmx -l results.jtl -e -o report

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-html-report
          path: report
